### PR TITLE
add Rhistory and Rproj.user to gitignore

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo could you take a look?

**Comment by rpitingolo** [comment]
You need to use the wildcard *, so it would be *..Rhistory instead of just .Rhistory

**Comment by maggiesu0725** [comment]
I copy pasted the gitignore content from RegHsg framework folder which should cover everything. @rpitingolo

**Comment by maggiesu0725** [comment]
@lhendey

**Comment by lhendey** [comment]
@maggiesu0725 it doesn't look like you followed @rpitingolo instruction?

**Comment by maggiesu0725** [comment]
I copy pasted the ignore file from regional housing directory. can change to wildcard format but they won't be consistent. @lhendey

**Comment by lhendey** [comment]
@maggiesu0725  - if you are certain its working correctly without the * go ahead and merge.

**Pull request merged**
